### ISSUE TITLE
28/12-Problema con pintar actor en canvas

### ISSUE THREAD

**Issue by S1t0** [S1t0/Space-InCore#3]
Voy a documentarme mejor y solucionar el problema del pintado del actor principal, ya que no consigo que salga, importo los demas archivos de js al script.js pero no consigo que se pinte.

**Comment by amargopastor** [comment]
@S1t0 que tal vas con esta parte? conseguiste el pintado? Sino nos cuentas ahora en la tutoría. Ánimo Ándres! 🚀 🚀 🚀
