### ISSUE TITLE
Quitar bug  movimiento al actor principal, terminar el requestanimationframe

### ISSUE THREAD

**Issue by S1t0** [S1t0/Space-InCore#4]
Tengo el actor pintado, necesito darle movimiento correcto ya que se pinta todo el recorrido que va haciendo el actor, y terminar el requestanimationframe.

**Comment by Alvaro-Lucas** [comment]
![image](https://user-images.githubusercontent.com/33863370/147705790-cd35cb74-a000-4fcc-a2c8-60540e65565a.png)

**Pregunta: ¿Estas seguro que el tamaño de tu canvas es 500x400?**
![image](https://user-images.githubusercontent.com/33863370/147706001-77e2c22b-e839-472e-b978-93954fe364c9.png)

Esto es lo que pasa cuando "hardcodeas" código. Si luego se cambia algo las cosas dejan de funcionar 🤣. Utiliza las propiedades del propio canvas para definir este tipo de datos, y te ahorraras muchos problemas en el futuro.
