### ISSUE TITLE
Delimitar limites de mi actor y terminar el contador de FPS

### ISSUE THREAD

**Issue by S1t0** [S1t0/Space-InCore#5]
No soy capaz de que mi actor tome los limites del canvas, y al hacer el contador de fps no me sale por pantalla

**Comment by Alvaro-Lucas** [comment]
Lo vemos en la tutoría de hoy.

Para que tenga en cuenta los limites del canvas, tendrás que indicárselo de alguna forma y controlar, cuando se vaya a mover, que aun tiene espacio para hacerlo.
